eula = (
    "PyWitch Client is a GUI interface to PyWitch library combined "
    "with a Web Application Framework (Flask).\n\n"
    "Its main purpose is to provide HTTP endpoint to get the lastest "
    "Twitch events captured with PyWitch.\n\n"
    "To do so, PyWitch requires OAuth token authentication. "
    "PyWitch Client includes an automatic token generator "
    "service, which, after you authorize it in Twitch, server side "
    "generate your token server with the following scopes :\n\n"
    "channel:read:redemptions\n"
    "channel:read:redemptions\n"
    "user:read:email\n"
    "chat:edit\n"
    "chat:read\n\n"
    "Your token will be stored in pywitch_client_config.ini to avoid "
    "subsequent token generation.\n\n"
    "Your token will be stored in server for a maximum of 120 seconds"
    " and it will be destroyed from server after PyWitch Client "
    "request it. Server will only store your Twitch user_id and "
    "public information, like display_name."
)
